# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WÃªreldbeskouing
subtitle: "'n Versameling van gespreksgidse oor die Christelike geloof"
description: saamgestel deur Attie Retief vir gebruik deur besprekingsgroepe van die Gereformeerde Kerk Bellville Oos
# GitHub Pages will automatically set baseurl to the repository name
# For local development, use empty baseurl
baseurl: "/GKBOReekse" # the subpath of your site, e.g. /blog
url: "https://attieretief.github.io" # the base hostname & protocol for your site
github_repo: GKBOReekse # the GitHub repo name for your project
github_username: attieretief # your GitHub username
owner: Attie Retief

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
# social_link: twitter
# social_username: broccolini

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: light

# Build settings
markdown: kramdown

# GitHub Pages only supports these plugins:
# https://pages.github.com/versions/
plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-titles-from-headings

collections:
  courses:
    output: true
    sort_by: lesson
